// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLdSLey07OOMPlr8pKHW-1ieG0T4aVGM',
    appId: '1:797104186476:web:e4a147b770c8aec7bb2449',
    messagingSenderId: '797104186476',
    projectId: 'chat-app-4534b',
    authDomain: 'chat-app-4534b.firebaseapp.com',
    storageBucket: 'chat-app-4534b.appspot.com',
    measurementId: 'G-CRCMTMSVFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzk1BwHNRq_Xt-GS46Nm_AJLhJykxSAUI',
    appId: '1:797104186476:android:09554035feda8382bb2449',
    messagingSenderId: '797104186476',
    projectId: 'chat-app-4534b',
    storageBucket: 'chat-app-4534b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzEFlcY9z8R--UZa16o3kk0D7oEzXVWXE',
    appId: '1:797104186476:ios:3456d56aa27e82f0bb2449',
    messagingSenderId: '797104186476',
    projectId: 'chat-app-4534b',
    storageBucket: 'chat-app-4534b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzEFlcY9z8R--UZa16o3kk0D7oEzXVWXE',
    appId: '1:797104186476:ios:3456d56aa27e82f0bb2449',
    messagingSenderId: '797104186476',
    projectId: 'chat-app-4534b',
    storageBucket: 'chat-app-4534b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuLdSLey07OOMPlr8pKHW-1ieG0T4aVGM',
    appId: '1:797104186476:web:f4772e91d01f8a33bb2449',
    messagingSenderId: '797104186476',
    projectId: 'chat-app-4534b',
    authDomain: 'chat-app-4534b.firebaseapp.com',
    storageBucket: 'chat-app-4534b.appspot.com',
    measurementId: 'G-G184LZGFCF',
  );
}
